[package]
name = "NumRS"
version = "0.0.1"
edition = "2021"


[lib]
name = "NumRS"
crate-type = ["cdylib"]  # This is the key to create a dynamic library
version = "0.0.1"
edition = "2021"
libloading = "0.7"

[dependencies]